---
- name: Kubernetes Persistent Volumes | Lay down OpenStack Cinder Storage Class template
  template:
    src: "openstack-storage-class.yml.j2"
    dest: "{{kube_config_dir}}/openstack-storage-class.yml"
  register: manifests
  when:
    - inventory_hostname == first_kube_master_host

- name: Kubernetes Persistent Volumes | Add OpenStack Cinder Storage Class
  kube:
    name: storage-class
    kubectl: "{{bin_dir}}/kubectl"
    resource: StorageClass
    filename: "{{kube_config_dir}}/openstack-storage-class.yml"
    state: "latest"
  when:
    - inventory_hostname == first_kube_master_host
    - manifests.changed
